### PR TITLE
nextTick was reimplemented

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
One of these days, I'll get travis setup :-)

```
TAP version 13
# AsyncArgs.select: subset of args is passed to next
ok 1 null
ok 2 should be equal
# AsyncArgs.select: jsonpointer works with object
ok 3 null
ok 4 should be equal
# AsyncArgs.select: jsonpointer works with array
ok 5 null
ok 6 should be equal
# AsyncArgs.select: jsonpointer works with multiple arguments
ok 7 null
ok 8 should be equal
ok 9 should be equal
# AsyncArgs.select: jsonpointer works with deeply nested object
ok 10 null
ok 11 should be equal
# AsyncArgs.select: array of jsonpointers 
ok 12 null
ok 13 should be equal
ok 14 should be equal
# asyncArgs.prependValues: prepends arguments to the next function
ok 15 null
ok 16 should be equal
# asyncArgs.appendValues: appends arguments to the next function
ok 17 null
ok 18 should be equal
# asyncArgs.values: sets arguments to the next function
ok 19 null
ok 20 should be equal
# asyncArgs.prependConstants: prepends arguments to the next function
ok 21 null
ok 22 should be equal
# asyncArgs.appendConstants: appends arguments to the next function
ok 23 null
ok 24 should be equal
# asyncArgs.constants: sets arguments to the next function
ok 25 null
ok 26 should be equal
# asyncArgs.store: passes through all values
ok 27 null
ok 28 should be equal
ok 29 should be equal
# asyncArgs.store: stores values for later retrieval
ok 30 null
ok 31 should be equal
ok 32 should be equal

1..32
# tests 32
# pass  32

# ok

```

**Comment by ghost** [comment]
will this screw some people up?  Should nextTick be configurable?

**Comment by baens** [comment]
I don't think it will screw it up. Looks good to me!

:+1:

**Comment by ghost** [comment]
this fixes #3

**Pull request merged**
